# Generated by Django 3.1.7 on 2021-04-30 04:49

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('userID', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=100, verbose_name='Full Name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('father_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10)),
                ('number', models.CharField(max_length=10)),
                ('emergency_number', models.CharField(max_length=10)),
                ('userphoto', models.ImageField(blank=True, default=account.models.defaultphoto_path, max_length=255, null=True, upload_to=account.models.userphoto_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
