# Generated by Django 3.1.7 on 2021-04-30 05:17

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210430_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='userphoto',
            field=models.ImageField(blank=True, default=account.models.defaultphoto_path, max_length=255, null=True, upload_to=account.models.userphoto_path, verbose_name='Photo'),
        ),
    ]
