# Generated by Django 3.1.7 on 2021-05-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210430_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+ve', 'A+'), ('A-ve', 'A-'), ('B+ve', 'B+'), ('B-ve', 'B-'), ('O+ve', 'O+'), ('O-ve', 'O-'), ('AB+ve', 'AB+'), ('AB-ve', 'AB-')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
